// Writes the contract ABIs and the deployed addresses into the website as typed TypeScript.
//   npm run export-abis
const fs = require("fs");
const path = require("path");

const ARTIFACTS = path.join(__dirname, "..", "artifacts", "src");
const OUT = path.join(__dirname, "..", "..", "web", "src", "generated");
const CONTRACTS = {
  optionsAbi: "XStockFiOptions.sol/XStockFiOptions.json",
  binariesAbi: "XStockFiBinaries.sol/XStockFiBinaries.json",
  incomeVaultAbi: "XStockFiIncomeVault.sol/XStockFiIncomeVault.json",
  liquidityVaultAbi: "XStockFiLiquidityVault.sol/XStockFiLiquidityVault.json",
  creditDeskAbi: "XStockFiCreditDesk.sol/XStockFiCreditDesk.json",
  buyBurnAbi: "XStockFiBuyBurn.sol/XStockFiBuyBurn.json",
  feeRouterAbi: "XStockFiFeeRouter.sol/XStockFiFeeRouter.json",
  oracleAbi: "XStockFiOracle.sol/XStockFiOracle.json",
  registryAbi: "XStockFiRegistry.sol/XStockFiRegistry.json",
};

fs.mkdirSync(OUT, { recursive: true });
const header = "// Generated by contracts/scripts/export-abis.js. Do not edit.\n\n";

let abis = header;
for (const [name, file] of Object.entries(CONTRACTS)) {
  const { abi } = JSON.parse(fs.readFileSync(path.join(ARTIFACTS, file), "utf8"));
  abis += `export const ${name} = ${JSON.stringify(abi)} as const;\n\n`;
}
fs.writeFileSync(path.join(OUT, "abis.ts"), abis);

// The live deployment always; the local demo too, so `NEXT_PUBLIC_ENABLE_LOCAL=1 npm run dev` can show it.
const deployments = {};
const dir = path.join(__dirname, "..", "deployments");
for (const f of ["robinhood.json", "localhost.json"]) {
  const file = path.join(dir, f);
  if (!fs.existsSync(file)) continue;
  const d = JSON.parse(fs.readFileSync(file, "utf8"));
  delete d.roles;
  delete d.pendingTimelockAcceptances;
  deployments[d.chainId] = d;
}
fs.writeFileSync(
  path.join(OUT, "deployments.ts"),
  header +
    `export type Addr = \`0x\${string}\`;

export type Deployment = {
  network: string;
  chainId: number;
  block: number;
  usdg: Addr;
  token: Addr | null;
  tokenSymbol?: string;
  tokenName?: string;
  oracle: Addr;
  options: Addr;
  binaries: Addr;
  buyBurn: Addr;
  feeRouter: Addr;
  registry: Addr;
  timelock: Addr;
  swapAdapter: Addr;
  markets: Record<string, { token: Addr; feed: Addr; name: string }>;
  incomeVaults: Record<string, { vault: Addr; stock: Addr; name: string }>;
  liquidityVaults: Record<string, { vault: Addr; position: Addr; stock: Addr; name: string }>;
  creditLines: Record<string, Addr>;
};

export const deployments: Record<number, Deployment> = ${JSON.stringify(deployments, null, 2)} as Record<number, Deployment>;
`,
);

const config = require("../config/robinhood.json");
const catalog = {
  chainId: config.network.chainId,
  explorer: config.network.explorer,
  usdg: config.tokens.usdg.address,
  ponsPage: config.pons.tokenPageUrl,
  stocks: Object.fromEntries(Object.entries(config.stockTokens).map(([t, v]) => [t, { name: v.name, address: v.address }])),
  launch: {
    markets: config.launch.markets,
    incomeVaults: config.launch.incomeVaults,
    liquidityVaults: config.launch.liquidityVaults,
    creditLines: config.launch.creditLines,
  },
};
fs.writeFileSync(path.join(OUT, "catalog.ts"), header + `export const catalog = ${JSON.stringify(catalog, null, 2)} as const;\n`);

console.log(`Exported ${Object.keys(CONTRACTS).length} ABIs and ${Object.keys(deployments).length} deployment(s) to web/src/generated`);
